### ISSUE TITLE
Git process fails since some time

### ISSUE THREAD

**Issue by st3iny** [ChristophWurst/conventional-nextcloud-npm-release#2]
The release action fails while fetching from git in multiple repositories. I first saw this failure in [nextcloud/calendar-js](https://github.com/nextcloud/calendar-js/actions/workflows/release.yml) and now also in [nextcloud/calendar-availability-vue](https://github.com/nextcloud/calendar-availability-vue/actions/workflows/release.yml). At least on cal-avail-vue it worked fine in the past.

The error indicates an authentication failure. AFAIK, the secrets have not been changed in a long time.

### Error message

```
/usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
The process '/usr/bin/git' failed with exit code 128
Waiting 20 seconds before trying again
```

### Examples

- https://github.com/nextcloud/calendar-availability-vue/actions/runs/9172206038/job/25218198718
- https://github.com/nextcloud/calendar-js/actions/runs/9002415016/job/24730663523

**Comment by ChristophWurst** [comment]
the github access token might be inaccessible or has expired

**Comment by ChristophWurst** [comment]
tokens had expired
